version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build completed on `date`
      - mvn clean package -DskipTests=true
      - ls -al target/
  post_build:
    commands:
      - echo Build completed on `data`
artifacts:
  files:
    - target/*.jar
  discard-paths: yes